/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ASYMLOGNORM
#define ASYMLOGNORM

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class AsymLogNorm : public RooAbsReal {
public:
  AsymLogNorm() {} ; 
  AsymLogNorm(const char *name, const char *title,
	      RooAbsReal& _beta_nsig,
	      RooAbsReal& _nsig_kappa_neg,
	      RooAbsReal& _nsig_kappa_pos);
  AsymLogNorm(const AsymLogNorm& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new AsymLogNorm(*this,newname); }
  inline virtual ~AsymLogNorm() { }

protected:

  RooRealProxy beta_nsig ;
  RooRealProxy nsig_kappa_neg ;
  RooRealProxy nsig_kappa_pos ;
  
  Double_t evaluate() const ;

private:

  ClassDef(AsymLogNorm,1) // Your description goes here...
};
 
#endif
