/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

// class declaration include file below retrieved from workspace code storage
#include "PowFunc.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(PowFunc) 

 PowFunc::PowFunc(const char *name, const char *title, 
                        RooAbsReal& x,
                        RooAbsReal& y) :
   RooAbsReal(name,title), 
  x_("x","",this,x),
  y_("y","",this,y)
{ 
} 


 PowFunc::PowFunc(const PowFunc& other, const char* name) :  
   RooAbsReal(other,name), 
   x_("x",this,other.x_),
   y_("y",this,other.y_)
 { 
 } 



 Double_t PowFunc::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return pow(x_,y_) ; 
 } 



