/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

// class declaration include file below retrieved from workspace code storage
#include "SqrtOfSqs.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(SqrtOfSqs) 

SqrtOfSqs::SqrtOfSqs(const char *name, const char *title, 
		     RooAbsReal& p0,RooAbsReal& p1):
  RooAbsReal(name,title), 
  p0_("p0","",this,p0),
  p1_("p1","",this,p1)
{ 
} 


 SqrtOfSqs::SqrtOfSqs(const SqrtOfSqs& other, const char* name) :  
   RooAbsReal(other,name), 
   p0_("p0",this,other.p0_),
   p1_("p1",this,other.p1_)
 { 
 } 



 Double_t SqrtOfSqs::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return std::sqrt(p0_*p0_ + p1_*p1_);
 } 



