/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEMUONTRIGGERUNCERT
#define ZPRIMEMUONTRIGGERUNCERT

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeMuonTriggerUncert : public RooAbsReal {
public:
  ZPrimeMuonTriggerUncert() {} ; 
  ZPrimeMuonTriggerUncert(const char *name, const char *title,
		       RooAbsReal& zPrimeMass,
		       RooAbsReal& cat,
		       RooAbsReal& add);
  ZPrimeMuonTriggerUncert(const ZPrimeMuonTriggerUncert& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeMuonTriggerUncert(*this,newname); }
  inline virtual ~ZPrimeMuonTriggerUncert() { }

protected:
  RooRealProxy zPrimeMass_;
  RooRealProxy cat_;
  RooRealProxy add_;

  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeMuonTriggerUncert,1) // Your description goes here...
};
 
#endif
