/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
o *****************************************************************************/

#ifndef ZPRIMEELEBKGPDF
#define ZPRIMEELEBKGPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeEleBkgPdf : public RooAbsPdf {
public:
  ZPrimeEleBkgPdf() {} ; 
  ZPrimeEleBkgPdf(const char *name, const char *title,
              RooAbsReal& _mass,
              RooAbsReal& _bkg_a,
              RooAbsReal& _bkg_b,
              RooAbsReal& _bkg_c,
              RooAbsReal& _bkg_d,
              RooAbsReal& _bkg_syst_a,
              RooAbsReal& _bkg_syst_b);
  ZPrimeEleBkgPdf(const ZPrimeEleBkgPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeEleBkgPdf(*this,newname); }
  inline virtual ~ZPrimeEleBkgPdf() { }

protected:

  RooRealProxy mass ;
  RooRealProxy bkg_a ;
  RooRealProxy  bkg_b ;
  RooRealProxy  bkg_c ;
  RooRealProxy  bkg_d ;
  RooRealProxy  bkg_syst_a ;
  RooRealProxy  bkg_syst_b ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeEleBkgPdf,1) // Your description goes here...
};
 
#endif
