/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEBKGPDFSLOW_H
#define ZPRIMEBKGPDFSLOW_H

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeBkgPdfSlow : public RooAbsPdf {
public:
  ZPrimeBkgPdfSlow() {} ; 
  ZPrimeBkgPdfSlow(const char *name, const char *title,
	      RooAbsReal& _mass,
	      RooAbsReal& _bkg_a,
	      RooAbsReal& _bkg_b,
	      RooAbsReal& _bkg_c,
	      RooAbsReal& _bkg_d,
	      RooAbsReal& _bkg_syst_a,
	      RooAbsReal& _bkg_syst_b);
  ZPrimeBkgPdfSlow(const ZPrimeBkgPdfSlow& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeBkgPdfSlow(*this,newname); }
  inline virtual ~ZPrimeBkgPdfSlow() { }

protected:

  RooRealProxy mass ;
  RooRealProxy bkg_a ;
  RooRealProxy bkg_b ;
  RooRealProxy bkg_c ;
  RooRealProxy bkg_d ;
  RooRealProxy bkg_syst_a ;
  RooRealProxy bkg_syst_b ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeBkgPdfSlow,1) // Your description goes here...
};
 
#endif
