/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEELERESFUNC_H
#define ZPRIMEELERESFUNC_H

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeEleResFunc : public RooAbsReal {
public:
  ZPrimeEleResFunc() {} ; 
  ZPrimeEleResFunc(const char *name, const char *title,
	      RooAbsReal& _res_scale,
	      RooAbsReal& _res_s,
	      RooAbsReal& _peak,
	      RooAbsReal& _res_n,
	      RooAbsReal& _res_c,
	      RooAbsReal& _res_slope);
  ZPrimeEleResFunc(const ZPrimeEleResFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeEleResFunc(*this,newname); }
  inline virtual ~ZPrimeEleResFunc() { }

protected:

  RooRealProxy res_scale ;
  RooRealProxy res_s ;
  RooRealProxy peak ;
  RooRealProxy res_n ;
  RooRealProxy res_c ;
  RooRealProxy res_slope ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeEleResFunc,1) // Your description goes here...
};
 
#endif
