/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEMUONRESSYS_H
#define ZPRIMEMUONRESSYS_H

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeMuonResSys : public RooAbsReal {
public:
  ZPrimeMuonResSys() {} ; 
  ZPrimeMuonResSys(const char *name, const char *title,
	      RooAbsReal& _peak,
	      RooAbsReal& _sys_a,
	      RooAbsReal& _sys_b,
	      RooAbsReal& _sys_c,
		   RooAbsReal& _peakCutOff);
  ZPrimeMuonResSys(const ZPrimeMuonResSys& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeMuonResSys(*this,newname); }
  inline virtual ~ZPrimeMuonResSys() { }

protected:

  RooRealProxy peak ;
  RooRealProxy sys_a ;
  RooRealProxy sys_b ;
  RooRealProxy sys_c ;
  RooRealProxy peakCutOff ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeMuonResSys,1) // Your description goes here...
};
 
#endif
