/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEELEACCEFFFUNC
#define ZPRIMEELEACCEFFFUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeEleAccEffFunc : public RooAbsReal {
public:
  ZPrimeEleAccEffFunc() {} ; 
  ZPrimeEleAccEffFunc(const char *name, const char *title,
	      RooAbsReal& _eff_scale,
	      RooAbsReal& _eff_a,
	      RooAbsReal& _eff_b,
	      RooAbsReal& _peak,
	      RooAbsReal& _eff_c,
	      RooAbsReal& _eff_d,
	      RooAbsReal& _eff_e);
  ZPrimeEleAccEffFunc(const ZPrimeEleAccEffFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeEleAccEffFunc(*this,newname); }
  inline virtual ~ZPrimeEleAccEffFunc() { }

protected:

  RooRealProxy eff_scale ;
  RooRealProxy eff_a ;
  RooRealProxy eff_b ;
  RooRealProxy peak ;
  RooRealProxy eff_c ;
  RooRealProxy eff_d ;
  RooRealProxy eff_e ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeEleAccEffFunc,1) // Your description goes here...
};
 
#endif
