/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEMUONACCEFFFUNC
#define ZPRIMEMUONACCEFFFUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeMuonAccEffFunc : public RooAbsReal {
public:
  ZPrimeMuonAccEffFunc() {} ; 
  ZPrimeMuonAccEffFunc(const char *name, const char *title,
		       RooAbsReal& zPrimeMass,
		       RooAbsReal& effScale,
		       RooAbsReal& effA,
		       RooAbsReal& effB,
		       RooAbsReal& effC,
		       RooAbsReal& effD,
		       RooAbsReal& trigA,
		       RooAbsReal& trigB,
		       RooAbsReal& tribC);
  ZPrimeMuonAccEffFunc(const ZPrimeMuonAccEffFunc& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeMuonAccEffFunc(*this,newname); }
  inline virtual ~ZPrimeMuonAccEffFunc() { }

protected:
  RooRealProxy zPrimeMass_;
  RooRealProxy effScale_;
  RooRealProxy effA_;
  RooRealProxy effB_;
  RooRealProxy effC_;
  RooRealProxy effD_;
  RooRealProxy trigA_;
  RooRealProxy trigB_;
  RooRealProxy trigC_;

  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeMuonAccEffFunc,1) // Your description goes here...
};
 
#endif
