/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEMUONACCEFFFUNCBENEG
#define ZPRIMEMUONACCEFFFUNCBENEG

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeMuonAccEffFuncBEneg : public RooAbsReal {
public:
  ZPrimeMuonAccEffFuncBEneg() {} ; 
  ZPrimeMuonAccEffFuncBEneg(const char *name, const char *title,
		       RooAbsReal& zPrimeMass,
		       RooAbsReal& effScale,
		       RooAbsReal& effA,
		       RooAbsReal& effB,
		       RooAbsReal& effC,
		       RooAbsReal& effD,
		       RooAbsReal& trigA,
		       RooAbsReal& trigB,
		       RooAbsReal& tribC);
  ZPrimeMuonAccEffFuncBEneg(const ZPrimeMuonAccEffFuncBEneg& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeMuonAccEffFuncBEneg(*this,newname); }
  inline virtual ~ZPrimeMuonAccEffFuncBEneg() { }

protected:
  RooRealProxy zPrimeMass_;
  RooRealProxy effScale_;
  RooRealProxy effA_;
  RooRealProxy effB_;
  RooRealProxy effC_;
  RooRealProxy effD_;
  RooRealProxy trigA_;
  RooRealProxy trigB_;
  RooRealProxy trigC_;

  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeMuonAccEffFuncBEneg,1) // Your description goes here...
};
 
#endif
