/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ZPRIMEMUONACCEFFFUNCBB
#define ZPRIMEMUONACCEFFFUNCBB

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ZPrimeMuonAccEffFuncBB : public RooAbsReal {
public:
  ZPrimeMuonAccEffFuncBB() {} ; 
  ZPrimeMuonAccEffFuncBB(const char *name, const char *title,
		       RooAbsReal& zPrimeMass,
		       RooAbsReal& effScale,
		       RooAbsReal& effA,
		       RooAbsReal& effB,
		       RooAbsReal& effC,
		       RooAbsReal& trigA,
                       RooAbsReal& trigB,
                       RooAbsReal& trigC);
  ZPrimeMuonAccEffFuncBB(const ZPrimeMuonAccEffFuncBB& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ZPrimeMuonAccEffFuncBB(*this,newname); }
  inline virtual ~ZPrimeMuonAccEffFuncBB() { }

protected:
  RooRealProxy zPrimeMass_;
  RooRealProxy effScale_;
  RooRealProxy effA_;
  RooRealProxy effB_;
  RooRealProxy effC_;
  RooRealProxy trigA_;
  RooRealProxy trigB_;
  RooRealProxy trigC_;
  
  Double_t evaluate() const ;

private:

  ClassDef(ZPrimeMuonAccEffFuncBB,1) // Your description goes here...
};
 
#endif
