/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

// class declaration include file below retrieved from workspace code storage
#include "ZPrimeBkgPdfSlow.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(ZPrimeBkgPdfSlow) 

 ZPrimeBkgPdfSlow::ZPrimeBkgPdfSlow(const char *name, const char *title, 
                        RooAbsReal& _mass,
                        RooAbsReal& _bkg_a,
                        RooAbsReal& _bkg_b,
                        RooAbsReal& _bkg_c,
                        RooAbsReal& _bkg_d,
                        RooAbsReal& _bkg_syst_a,
                        RooAbsReal& _bkg_syst_b) :
   RooAbsPdf(name,title), 
   mass("mass","mass",this,_mass),
   bkg_a("bkg_a","bkg_a",this,_bkg_a),
   bkg_b("bkg_b","bkg_b",this,_bkg_b),
   bkg_c("bkg_c","bkg_c",this,_bkg_c),
   bkg_d("bkg_d","bkg_d",this,_bkg_d),
   bkg_syst_a("bkg_syst_a","bkg_syst_a",this,_bkg_syst_a),
   bkg_syst_b("bkg_syst_b","bkg_syst_b",this,_bkg_syst_b)
 { 
 } 


 ZPrimeBkgPdfSlow::ZPrimeBkgPdfSlow(const ZPrimeBkgPdfSlow& other, const char* name) :  
   RooAbsPdf(other,name), 
   mass("mass",this,other.mass),
   bkg_a("bkg_a",this,other.bkg_a),
   bkg_b("bkg_b",this,other.bkg_b),
   bkg_c("bkg_c",this,other.bkg_c),
   bkg_d("bkg_d",this,other.bkg_d),
   bkg_syst_a("bkg_syst_a",this,other.bkg_syst_a),
   bkg_syst_b("bkg_syst_b",this,other.bkg_syst_b)
 { 
 } 



 Double_t ZPrimeBkgPdfSlow::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return exp(mass*bkg_a+mass*mass*bkg_b+mass*mass*mass*bkg_c)*pow(mass,bkg_d)*(bkg_syst_a+bkg_syst_b*mass) ; 
 } 



